<h5>Raw data</h5>

In [3]:
import numpy as np
import pandas as pd
import scipy
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

tickers = ['^NYA', 'BAC', 'C', 'CL', 'CVS', 'CVX', 'DIS', 'F', 'IBM', 'JNJ', 'KO', 'MMM', 'MRK', 'XOM', 'WFC']
consolidated = pd.DataFrame()
for ticker in tickers:
    df = yf.Ticker(ticker).history(period='max', interval='1d', auto_adjust=True).drop(columns=['Volume', 'Dividends', 'Stock Splits']).rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close'}).round(5)
    df[ticker] = df['close']
    consolidated = pd.concat([consolidated, df[ticker]], axis=1)
consolidated.dropna()

,^NYA,BAC,C,CL,CVS,CVX,DIS,F,IBM,JNJ,KO,MMM,MRK,XOM,WFC
1977-01-03,610.00000,0.54990,7.69720,0.44417,0.70903,1.09995,0.64285,0.33121,4.55186,0.56142,0.21710,1.65677,0.42979,0.44661,0.23744
1977-01-04,603.44000,0.54990,7.72178,0.44011,0.69231,1.08303,0.62576,0.32175,4.49425,0.55334,0.21468,1.63836,0.42498,0.43932,0.23744
1977-01-05,598.37000,0.55551,7.67261,0.44011,0.68562,1.07288,0.62576,0.31770,4.51071,0.55154,0.21122,1.62732,0.42097,0.43828,0.23325
1977-01-06,600.06000,0.56112,7.62342,0.43605,0.69565,1.07626,0.61721,0.32310,4.51071,0.55424,0.21433,1.63100,0.42658,0.43932,0.23534
1977-01-07,600.47998,0.57234,7.64801,0.43808,0.68896,1.08642,0.61721,0.32513,4.47778,0.55244,0.21295,1.63836,0.42818,0.44036,0.23325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-11,16534.19922,39.59000,50.55000,80.44000,104.45000,165.56000,130.64999,15.28000,126.37000,179.84000,63.81000,150.12000,86.63000,83.85000,49.33000
2022-04-12,16465.99023,39.17000,50.34000,81.00000,104.64000,169.00999,130.84000,15.36000,125.98000,179.89999,64.56000,148.58000,85.63000,85.60000,48.42000
2022-04-13,16614.78906,38.82000,50.15000,80.99000,104.98000,171.67000,132.35001,15.51000,126.14000,180.66000,64.73000,148.66000,86.13000,86.81000,48.54000
2022-04-14,16511.50977,37.57000,50.93000,80.94000,103.68000,171.59000,130.47000,15.48000,126.56000,179.89999,65.02000,147.38000,86.91000,87.83000,46.35000
2022-04-18,16466.21094,38.85000,52.31000,80.01000,103.42000,173.89000,127.77000,15.67000,126.17000,177.66000,64.44000,146.17999,86.07000,88.55000,47.17000

<h4>RSL - Relative Strength to Levy</h4>

In [4]:
p = 10
tickers = ['^NYA', 'BAC', 'C', 'CL', 'CVS', 'CVX', 'DIS', 'F', 'IBM', 'JNJ', 'KO', 'MMM', 'MRK', 'XOM', 'WFC']
for ticker in tickers:
    consolidated[f'RSL_{ticker}'] = (consolidated[ticker] / consolidated[ticker].rolling(window=p).mean() - 1) * 100
consolidated.dropna()

,^NYA,BAC,C,CL,CVS,CVX,DIS,F,IBM,JNJ,...,RSL_CVX,RSL_DIS,RSL_F,RSL_IBM,RSL_JNJ,RSL_KO,RSL_MMM,RSL_MRK,RSL_XOM,RSL_WFC
1977-01-14,595.94000,0.57234,7.82016,0.40563,0.73578,1.09318,0.63601,0.32851,4.45309,0.52999,...,0.968790,2.365639,0.829942,-0.542349,-3.261606,-1.581391,-4.956531,-1.908051,-0.496293,0.177079
1977-01-17,594.56000,0.57234,7.64801,0.40360,0.73578,1.09657,0.62234,0.32648,4.49425,0.52280,...,1.313527,0.497206,0.352562,0.506260,-3.896529,-2.078458,-4.467017,-2.791656,-1.160474,-1.138478
1977-01-18,592.54999,0.56673,7.67261,0.39752,0.72575,1.10334,0.60866,0.32783,4.53129,0.52100,...,1.748089,-1.439719,0.579553,1.250727,-3.654651,-1.858404,-4.059219,-2.629715,-1.043317,-1.704901
1977-01-19,595.94000,0.56673,7.69720,0.40317,0.71906,1.11688,0.60695,0.32919,4.56833,0.52100,...,2.580493,-1.416343,0.642025,1.947121,-3.107443,-1.185281,-1.806180,-1.851287,-0.522020,-3.173008
1977-01-20,591.39001,0.56673,7.64801,0.40521,0.69899,1.09657,0.59327,0.32716,4.49425,0.51112,...,0.527587,-3.262153,-0.102597,0.330801,-4.176439,-1.306949,-2.421869,-4.807930,-0.878829,-2.757344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-11,16534.19922,39.59000,50.55000,80.44000,104.45000,165.56000,130.64999,15.28000,126.37000,179.84000,...,0.219130,-3.839085,-5.527390,-2.450132,0.313480,1.538755,0.033986,2.784666,0.162458,0.848411
2022-04-12,16465.99023,39.17000,50.34000,81.00000,104.64000,169.00999,130.84000,15.36000,125.98000,179.89999,...,2.017898,-2.874281,-3.608409,-2.301702,0.226187,2.341360,-0.760757,1.111124,1.859895,-0.364220
2022-04-13,16614.78906,38.82000,50.15000,80.99000,104.98000,171.67000,132.35001,15.51000,126.14000,180.66000,...,3.237796,-1.121389,-1.580049,-1.721088,0.589641,2.202574,-0.523279,1.255555,2.928622,0.206441
2022-04-14,16511.50977,37.57000,50.93000,80.94000,103.68000,171.59000,130.47000,15.48000,126.56000,179.89999,...,2.648928,-2.036312,-0.870902,-1.127317,0.017787,2.173264,-1.280711,1.592089,3.495004,-3.895996
2022-04-18,16466.21094,38.85000,52.31000,80.01000,103.42000,173.89000,127.77000,15.67000,126.17000,177.66000,...,3.426536,-3.394099,0.979508,-1.124564,-1.198452,1.012634,-1.853760,0.311178,3.680026,-1.882475